name: .NET Build, Test, and Publish Nuget Package

on:
  push:
    branches:
      - "**"
    tags: 
      - "v*"
  pull_request:
    branches:
      - "**"
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ./ShortCleanLinqExtensions

defaults:
  run:
    working-directory: ./ShortCleanLinqExtensions
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Version Variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore 

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Setup node to create release 
      uses: actions/setup-node@v2
      with:
            node-version: '20'

    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 18.0.1
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/github
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create package
      run: dotnet pack --configuration Release --output nupkgs
   
    - name: Publish NuGet package to nuget
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
