name: PULL REQUEST

on:
  push:
    branches:
      - "**"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ./ShortCleanLinqExtensions

defaults:
  run:
    working-directory: ./ShortCleanLinqExtensions
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore 

    - name: Test
      run: dotnet test --no-build --verbosity normal
